[project]
name = "numerical-statistics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "007", email = "007lookworld@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "bert-score>=0.3.13",
    "evaluate>=0.4.6",
    "jieba>=0.42.1",
    "matplotlib>=3.11.2",
    "nltk>=3.10.3",
    "numpy>=1.26.4",
    "pycocoevalcap>=1.2",
    "rouge-score>=0.1.2",
    "sacrebleu>=2.6.0",
    "scikit-learn>=1.9.1",
    "scipy>=1.17.1",
    "setuptools<81",
    "torch>=2.14.0",
    "unbabel-comet>=2.2.7",
]



